import { writeFileSync } from "fs";
import { config } from "dotenv";

// Load .env file to access environment variables
config();

// データベースの環境変数を取得
const {
  NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  NEXT_PUBLIC_FIREBASE_VAPID_KEY, // この項目も必要であれば
} = process.env;

// swEnv.js という名前で Firebase の設定情報を含んだ JavaScript ファイルを生成
const content = `const swEnv = {
    NEXT_PUBLIC_FIREBASE_API_KEY: '${NEXT_PUBLIC_FIREBASE_API_KEY}',
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: '${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: '${NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: '${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
    NEXT_PUBLIC_FIREBASE_APP_ID: '${NEXT_PUBLIC_FIREBASE_APP_ID}',
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: '${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}',
    NEXT_PUBLIC_FIREBASE_VAPID_KEY: '${NEXT_PUBLIC_FIREBASE_VAPID_KEY}'
 }`;

// Next.js の public フォルダに書き込む (最終的には /public/swEnv.js)
writeFileSync("./public/swEnv.js", content);
